name: mobile_flutter_engineer_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.0-99.1.beta <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  video_player: ^2.8.6
  http: ^1.2.1
  dio: ^5.4.3+1
  path_provider: ^2.1.3
  percent_indicator: ^4.2.3
  shimmer: ^3.0.0
  html_unescape: ^2.0.0
  flutter_slidable: ^3.1.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
